<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <OutDir>bin\$(Configuration)\</OutDir>
    <CAMPath>C:\repo\links\CamExe</CAMPath>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="EncySoftware.CAMAPI.SDK.Net" Version="1.4.1" />
<!--    <PackageReference Include="EncySoftware.CAMAPI.SDK.Net" Version="1.4.1-dev.26" />
      <Reference Include="$(CAMPath)\CAMAPI.ResultStatus.dll" />
      <Reference Include="$(CAMPath)\CAMAPI.DotnetHelper.dll" />
      <Reference Include="$(CAMPath)\CAMAPI.Application.dll" />
      <Reference Include="$(CAMPath)\CAMAPI.Extensions.dll" />
      <Reference Include="$(CAMPath)\CAMAPI.Singletons.dll" />
      <Reference Include="$(CAMPath)\CAMAPI.Project.dll" />
      <Reference Include="$(CAMPath)\CAMAPI.GeomImporter.dll" />
      <Reference Include="$(CAMPath)\STGeomApiTypes.dll" />
      <Reference Include="$(CAMPath)\Geometry.VecMatrLib.dll" />
      <Reference Include="$(CAMPath)\STTypes.dll" />-->
  </ItemGroup>
</Project>
