<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <OutDir>bin\$(Configuration)\</OutDir>
    <CAMPath>C:\Program Files\ENCY Software\ENCY 2\Bin64</CAMPath>
  </PropertyGroup>
 
  <ItemGroup>
    <PackageReference Include="EncySoftware.CAMAPI.Sdk.Net" Version="2.0.23" />
  </ItemGroup>
</Project>
