#pragma once
#include "oaidl.h"
#include "ocidl.h"
#include <Unknwn.h>
#include <CAMAPI.EventHandler.h>
#include <CAMAPI.Generic.List.h>
#include <STTypes.h>
#include <STXMLPropTypes.h>
#include <CAMAPI.Machine.h>
#include <CAMAPI.CurveTypes.h>
#include <CAMAPI.MeshTypes.h>
#include <CAMAPI.SurfaceTypes.h>
#include <CAMAPI.ModelFormerTypes.h>
#include <CAMAPI.CustomAttributes.h>
#include <STCustomPropTypes.h>
#include <CAMAPI.Tools.h>
#include <CAMAPI.Workpiece.h>
#include <CAMAPI.MachineConfiguration.h>
#include <CAMAPI.MCDFormerTypes.h>
#include <CAMAPI.TechOperation.h>
#include <CAMAPI.PartStage.h>
#include <CAMAPI.Technologist.h>
#include <CAMAPI.NCMaker.h>
#include <CAMAPI.EtalonProject.h>
#include <CAMAPI.GeomModel.h>
#include <CAMAPI.GeomLibrary.h>
#include <CAMAPI.GeomImporter.h>
#include <CAMAPI.ToolsList.h>
#include <CAMAPI.Snapshot.h>
#include <CAMAPI.CoordinateSystem.h>
#include <CAMAPI.Simulator.h>
#include <CAMAPI.Project.h>
#include <CAMAPI.TechnologyForm.h>
#include <CAMAPI.ApplicationMainForm.h>
#include <CAMAPI.Logger.h>
#include <STGeomApiTypes.h>
#include <CAMAPI.Singletons.h>
#include <CAMAPI.Extensions.h>
#include <CAMAPI.Extension.PLM.h>
#include <CAMAPI.MachinesLibrary.h>
#include <CAMAPI.Utilities.h>
#include <CAMAPI.Application.h>