<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <OutDir>bin</OutDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EncySoftware.CAMAPI.SDK.Net" Version="3.0.6"/>
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" GeneratePathProperty="true"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="$(PkgMathNet_Numerics)\lib\net6.0\MathNet.Numerics.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Link>%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="PartCalibrationWorkflowNet.settings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
