<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <OutDir>bin\$(Configuration)\</OutDir>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="EncySoftware.CAMAPI.Sdk.Net" Version="2.0.18-dev.9" />
  </ItemGroup>

    <ItemGroup>
        <None Update="ExtensionGlobalNet.settings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>